matrix:
  include:
    - os: linux
      language: python
      python:
        - 3.5
    - os: linux
      language: python
      python:
        - 3.6
    - os: linux
      language: python
      python:
        - 3.7
    - os: linux
      language: python
      python:
        - 3.8

cache:
  # must specify pip dir
  # https://github.com/travis-ci/travis-ci/issues/3239
  directories:
    - $HOME/virtualenv
    - $HOME/.cache/pip

env:
  global:
    # These two environment variables could be set by Travis itself, or Travis
    # could configure itself in /etc/, ~/, or inside of the virtual
    # environments. In any case if these two values get configured then end
    # users only need to enable the pip cache and manually run pip wheel before
    # running pip install.
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

before_install: |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    dev/install_pysqlite.sh
    pip install -U pip
    pip install check-manifest readme_renderer flake8 docutils
  else
    # see https://pythonhosted.org/CodeChat/.travis.yml.html
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    # A manual check that the correct version of Python is running.
    python --version
    pip install -U pip
    pip install check-manifest readme_renderer flake8 docutils
  fi

install:
  - pip install -U -e .

script:
  - python setup.py -q test
  - check-manifest --ignore
    "tox.ini,tests/**/*,testfiles/**/*,docs/*,taxtastic/data/*"
  - python setup.py check --metadata --restructuredtext --strict
  # - flake8 taxtastic
